[platformio]
default_envs = nucleo_h755zi_q_cm7, nucleo_h755zi_q_cm4

[env]
platform = ststm32
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200
build_flags =
  -DDEBUG
  -I/Users/krzysztof/.platformio/packages/framework-stm32cubeh7/Drivers/BSP/STM32H7xx_Nucleo
board_build.stm32cube.custom_config_header = yes

[env:nucleo_h755zi_q_cm7]
board = nucleo_h755zi_q_cm7
board_build.stm32cube.system_file = system_stm32h7xx_dualcore_bootcm7_cm4gated.c

[env:nucleo_h755zi_q_cm4]
board = nucleo_h755zi_q_cm4
board_build.stm32cube.system_file = system_stm32h7xx_dualcore_bootcm4_cm7gated.c
